-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 20:24:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema angry_zeta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema angry_zeta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `angry_zeta` DEFAULT CHARACTER SET utf8 ;
USE `angry_zeta` ;

-- -----------------------------------------------------
-- Table `angry_zeta`.`Galeria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angry_zeta`.`Galeria` ;

CREATE TABLE IF NOT EXISTS `angry_zeta`.`Galeria` (
  `id_galeria` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_galeria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angry_zeta`.`Merch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angry_zeta`.`Merch` ;

CREATE TABLE IF NOT EXISTS `angry_zeta`.`Merch` (
  `id_Merch` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Merch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `angry_zeta`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angry_zeta`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `angry_zeta`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Galeria VALUES (1,"galeria/1/1.jpg","El Emergente Bar");
INSERT INTO Galeria VALUES (2,"galeria/2/2.jpg","Barrio Chino");
INSERT INTO Galeria VALUES (3,"galeria/3/3.jpg","Valkiria Bar");
INSERT INTO Galeria VALUES (4,"galeria/4/4.jpg","San Martin de los Andes");
INSERT INTO Galeria VALUES (5,"galeria/5/5.jpg","Rancho Taxco");
INSERT INTO Galeria VALUES (6,"galeria/6/6.jpg","Ensayo en la casa de Zeta");
INSERT INTO Galeria VALUES (7,"galeria/7/7.jpg","Casamiento");
INSERT INTO Galeria VALUES (8,"galeria/8/8.jpg","Programa de Tv Cuatro Caras Bonitas");
INSERT INTO Galeria VALUES (9,"galeria/9/9.jpg","El Universal");
INSERT INTO Galeria VALUES (10,"galeria/10/10.jpg","Barrio Chino");
INSERT INTO Galeria VALUES (11,"galeria/11/11.jpg","El Universal");
INSERT INTO Galeria VALUES (12,"galeria/12/12.jpg","Festival Arte X Alma");
INSERT INTO Galeria VALUES (13,"galeria/13/13.jpg","Barrio Chino");

SELECT * FROM Galeria;
SELECT * FROM Merch;

INSERT INTO Merch VALUES (1,"merch/cd de estudio/cd de estudio.jpg","Primer CD de Estudio","CD Angry Zeta & The Hillbullys");
INSERT INTO Merch VALUES (2,"merch/cd en vivo/cd en vivo.jpg","CD grabado en Vivo","CD Angry Zeta & The Hillbullys");
INSERT INTO Merch VALUES (3,"merch/parche/parche.jpg","Parches bordados","Parche Angry Zeta & The Hillbullys");
INSERT INTO Merch VALUES (4,"merch/pin/pin.jpg","Pin de metal","Pin Angry Zeta & The Hillbullys");
INSERT INTO Merch VALUES (5,"merch/remera/remera.jpg","Remera de Angry Zeta & The Hillbullys","Remera de Angry Zeta & The Hillbullys");
INSERT INTO Merch VALUES (6,"merch/remera oso/remera oso.jpg","Remera con el logo del oso","Remera Angry Zeta & The Hillbullys");

SELECT * FROM Usuario;